### ISSUE TITLE
crawfish can't save

### ISSUE THREAD

**Issue by basicallynewbie** [drakonkat/webtorrent-express-api#14]
**Describe the bug**
I add a Magnet Link, but nothing happened. I try to change Download path, and hit save, but nothing happened, go to home and return, the path is empty again.
I also tried desktop version ,and it can't download too. The Magnet Link is working normal, because I can download it with qbittorrent.

**To Reproduce**
1. docker-compose
```
version: "3.9"
services:
  crawfish:
    image: mauromazzocchetti/crawfish
    container_name: crawfish
    volumes:
      - /home/me/docker/crawfish/downloads:/usr/src/app/Downloads
    ports:
      - 3015:3000
      - 51415:51415
    restart: unless-stopped
```
2. go to http://ip:3015/crawfish-official/index.html
3. Click on "add" and put in Magnet Link then hit "save and close", but nothing happened.
4. go to "settings",add a path in "Download path" then hit "save", but nothing happened. Go to home and return, the path is empty again.
5. Use desktop version, click on "add" and put in Magnet Link then hit "save and close",  start downloading but not showing name and no download speed.

**Expected behavior**
Add a Magnet Link then start downloading.

**Screenshots**
![crawfish](https://user-images.githubusercontent.com/107107611/201345910-c893d391-8b1d-41f3-9d24-c058c5d90987.PNG)
![setting](https://user-images.githubusercontent.com/107107611/201345949-e910b923-c311-46a3-a97f-da710859599a.PNG)
![desktop](https://user-images.githubusercontent.com/107107611/201352862-bb8d4bef-d92e-47d5-9c62-52209b2817bb.PNG)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chrome
 - Version 107.0.5304.106

**Additional context**
I can't find a button to upload a torrent file. /home/me/docker/crawfish/downloads is owned by me not root. 
logs showing in portainer:
```

> crawfish@1.7.18 prod
> node ./bin/www-prod

/bin/sh: 1: xdg-user-dir: not found
Starting the service... false true
Express server stared! Mode:  development
Error getting data at start:  Error [OpenError]: IO error: /root/Crawfish/config_db/LOCK: No such file or directory
    at /app/node_modules/levelup/lib/levelup.js:119:23
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14 {
  [cause]: undefined
}
Error reading file: /root/Crawfish/config.json
Error [OpenError]: IO error: /root/Crawfish/config_db/LOCK: No such file or directory
    at /app/node_modules/levelup/lib/levelup.js:119:23
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14 {
  [cause]: undefined
}
*** uncaughtException: Error [OpenError]: IO error: /root/Crawfish/config_db/LOCK: No such file or directory
    at /app/node_modules/levelup/lib/levelup.js:119:23
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14 {
  [cause]: undefined
}
*** uncaughtException: Error [OpenError]: IO error: /root/Crawfish/config_db/LOCK: No such file or directory
    at /app/node_modules/levelup/lib/levelup.js:119:23
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14 {
  [cause]: undefined
}
*** uncaughtException: Error [OpenError]: IO error: /root/Crawfish/config_db/LOCK: No such file or directory
    at /app/node_modules/levelup/lib/levelup.js:119:23
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14 {
  [cause]: undefined
}
*** uncaughtException: Error [OpenError]: IO error: /root/Crawfish/config_db/LOCK: No such file or directory
    at /app/node_modules/levelup/lib/levelup.js:119:23
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14 {
  [cause]: undefined
}
*** uncaughtException: TypeError: Cannot read properties of undefined (reading 'map')
    at ConfigStorage.getAllTorrent (/app/routes/classes/ConfigStorage.js:279:28)
    at async /app/routes/classes/ConfigStorage.js:145:32
```

**Comment by basicallynewbie** [comment]
The desktop version took a very long time to start download, and the download speed is very slow about 150 B/s, but at least donwloading. Docker version can't even start a task.

**Comment by drakonkat** [comment]
Really strange, seems to have no permission to write the local data

Actually this is my configuration on my PC that is working:

```
---
version: "3.9"
services:
  express:
    container_name: webtorrent
    image: mauromazzocchetti/crawfish:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - ./Downloads:/usr/src/app/Downloads
      - ./Crawfish:/root/Crawfish
    network_mode: host

```

If is possible can you try with this volume setted up?
